### ISSUE TITLE
Icons missing.

### ISSUE THREAD

**Issue by mcoyle1960** [gaheldev/pipewire-settings#1]
Great extension!

FYI, I installed using the Extensions Manager flatpak in Fedora 41/Gnome 47 and the icons folder was empty.  Odd.

Download the icons from here and it worked.

**Comment by gaheldev** [comment]
Thanks for the report!

Indeed I messed up the release. It should be ok once the next release is up :smile:

**Comment by mcoyle1960** [comment]
Glad to help. Thanks for your work.
